source: reliefweb
schema: corpusama/database/schema/reliefweb.sql
db_name: data/reliefweb_2000+.db
text_column: body_html
quota: 1000
wait_dict: {"0": 1, "5": 49, "10": 99, "20": 499, "30": null}
parameters:
  filter:
    conditions:
    - field: format
      negate: true
      value:
      - Map
      - Interactive
      - Infographic
      - Other
    - field: date
      value:
        from: '2000-01-01T00:00:00+00:00'
    operator: AND
  fields:
    exclude: [body]
  limit: 1000
  offset: 0
  profile: full
  slim: 1
  sort:
  - date.changed:asc
attributes:
  api_params_hash:
    MULTIVALUE: 0
    drop: true
    note: for referencing API calls history
  country__id:
    MULTIVALUE: 1
    drop: true
  country__iso3:
    MULTIVALUE: 1
  country__location__lat:
    MULTIVALUE: 1
    drop: true
  country__location__lon:
    MULTIVALUE: 1
    drop: true
  country__name:
    MULTIVALUE: 1
    drop: true
  country__primary:
    MULTIVALUE: 1
    drop: true
  country__shortname:
    MULTIVALUE: 1
  date__changed:
    MULTIVALUE: 1
    drop: true
  date__changed__year:
    MULTIVALUE: 1
    drop: true
    note: derived from date__changed
  date__created:
    MULTIVALUE: 1
    drop: true
  date__created__year:
    MULTIVALUE: 1
    drop: true
    note: derived from date__created
  date__original:
    MULTIVALUE: 1
  date__original__year:
    MULTIVALUE: 1
    note: derived from date__original
  disaster__glide:
    MULTIVALUE: 1
  disaster__id:
    MULTIVALUE: 1
    drop: true
  disaster__name:
    MULTIVALUE: 1
  disaster__status:
    MULTIVALUE: 1
    drop: true
  disaster_type__code:
    MULTIVALUE: 1
    drop: true
  disaster_type__id:
    MULTIVALUE: 1
    drop: true
  disaster_type__name:
    MULTIVALUE: 1
  feature__id:
    MULTIVALUE: 1
    drop: true
  feature__name:
    MULTIVALUE: 1
    drop: true
  file__description:
    MULTIVALUE: 1
    drop: true
  file__filename:
    MULTIVALUE: 1
    drop: true
  file__filesize:
    MULTIVALUE: 1
    drop: true
  file__id:
    MULTIVALUE: 1
    drop: true
  file__mimetype:
    MULTIVALUE: 1
    drop: true
  file__preview__url:
    MULTIVALUE: 1
    drop: true
  file__preview__url_large:
    MULTIVALUE: 1
    drop: true
  file__preview__url_small:
    MULTIVALUE: 1
    drop: true
  file__preview__url_thumb:
    MULTIVALUE: 1
    drop: true
  file__preview__version:
    MULTIVALUE: 1
    drop: true
  file__url:
    MULTIVALUE: 1
    drop: true
  format__id:
    MULTIVALUE: 1
    drop: true
  format__name:
    MULTIVALUE: 1
  headline__image__caption:
    MULTIVALUE: 1
    drop: true
  headline__image__copyright:
    MULTIVALUE: 1
    drop: true
  headline__image__filename:
    MULTIVALUE: 1
    drop: true
  headline__image__filesize:
    MULTIVALUE: 1
    drop: true
  headline__image__height:
    MULTIVALUE: 1
    drop: true
  headline__image__id:
    MULTIVALUE: 1
    drop: true
  headline__image__mimetype:
    MULTIVALUE: 1
    drop: true
  headline__image__url:
    MULTIVALUE: 1
    drop: true
  headline__image__url_large:
    MULTIVALUE: 1
    drop: true
  headline__image__url_small:
    MULTIVALUE: 1
    drop: true
  headline__image__url_thumb:
    MULTIVALUE: 1
    drop: true
  headline__image__width:
    MULTIVALUE: 1
    drop: true
  headline__summary:
    MULTIVALUE: 1
    drop: true
  headline__title:
    MULTIVALUE: 1
    drop: true
  id:
    MULTIVALUE: 0
  image__caption:
    MULTIVALUE: 1
    drop: true
  image__copyright:
    MULTIVALUE: 1
    drop: true
  image__filename:
    MULTIVALUE: 1
    drop: true
  image__filesize:
    MULTIVALUE: 1
    drop: true
  image__height:
    MULTIVALUE: 1
    drop: true
  image__id:
    MULTIVALUE: 1
    drop: true
  image__mimetype:
    MULTIVALUE: 1
    drop: true
  image__url:
    MULTIVALUE: 1
    drop: true
  image__url_large:
    MULTIVALUE: 1
    drop: true
  image__url_small:
    MULTIVALUE: 1
    drop: true
  image__url_thumb:
    MULTIVALUE: 1
    drop: true
  image__width:
    MULTIVALUE: 1
    drop: true
  language__code:
    MULTIVALUE: 1
    drop: true
  language__id:
    MULTIVALUE: 1
    drop: true
  language__name:
    MULTIVALUE: 1
    drop: true
  ocha_product__id:
    MULTIVALUE: 1
    drop: true
  ocha_product__name:
    MULTIVALUE: 1
    drop: true
  origin:
    MULTIVALUE: 0
    drop: true
  primary_country__id:
    MULTIVALUE: 1
    drop: true
  primary_country__iso3:
    MULTIVALUE: 1
  primary_country__location__lat:
    MULTIVALUE: 1
    drop: true
  primary_country__location__lon:
    MULTIVALUE: 1
    drop: true
  primary_country__name:
    MULTIVALUE: 1
    drop: true
  primary_country__shortname:
    MULTIVALUE: 1
  source__disclaimer:
    MULTIVALUE: 1
    drop: true
  source__homepage:
    MULTIVALUE: 1
    drop: true
  source__id:
    MULTIVALUE: 1
    drop: true
  source__longname:
    MULTIVALUE: 1
    drop: true
  source__name:
    MULTIVALUE: 1
  source__shortname:
    MULTIVALUE: 1
  source__spanish_name:
    MULTIVALUE: 1
  source__type__id:
    MULTIVALUE: 1
    drop: true
  source__type__name:
    MULTIVALUE: 1
  status:
    MULTIVALUE: 0
    drop: true
  theme__id:
    MULTIVALUE: 1
    drop: true
  theme__name:
    MULTIVALUE: 1
  title:
    MULTIVALUE: 0
  url:
    MULTIVALUE: 0
  url_alias:
    MULTIVALUE: 0
    drop: true
  body:
    drop: true
  body_html:
    drop: true
  disaster__type:
    drop: true
  feature:
    drop: true
  headline:
    drop: true
  image:
    drop: true
  vulnerable_groups:
    drop: true
    note: deprecated
  file:
    drop: true
  redirects:
    drop: true
  file_id:
    MULTIVALUE: 0
    note: supersedes file__id
  vulnerable_groups__id:
    drop: true
  ocha_product:
    drop: true
  vulnerable_groups__name:
    drop: true
